//
//  client.c
//  unix-programing
//
//  Created by yaya on 2019/12/19.
//  Copyright © 2019 西木柚子. All rights reserved.
//

#include    "../../unpipc.c"        /* our header */
#include    "square.h"        /* generated by rpcgen */


//MARK:- 单线程客户端
int
main(int argc, char **argv)
{
    CLIENT        *cl;
    square_in    in;
    square_out    *outp;

    if (argc != 3)
        err_quit("usage: client <hostname> <integer-value>");

    cl = clnt_create(argv[1], SQUARE_PROG, SQUARE_VERS, "tcp");

    in.arg1 = atol(argv[2]);
    if ( (outp = squareproc_1(&in, cl)) == NULL)
        err_quit("%s", clnt_sperror(cl, argv[1]));

    printf("result: %ld\n", outp->res1);
    exit(0);
}



